name: Deploy to LWS SFTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: nwtgck/actions-sftp@v2
        with:
          ssh-private-key: '' # Non utilisé si on passe par mot de passe
          remote-path: './' # Dossier distant sur ton serveur
          args: '-o StrictHostKeyChecking=no'
        env:
          SFTP_HOST: ${{ secrets.FTP_SERVER }}
          SFTP_PORT: '22'
          SFTP_USER: ${{ secrets.FTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          SFTP_REMOTE_PATH: './'
          SFTP_LOCAL_PATH: './'